<?php wp_nav_menu( [
    'theme_location'  => 'about',
    'menu'            => 'about',
    'container'       => 'nav',
    'container_class' => 'mini-menu',
    'container_id'    => '',
    'menu_class'      => 'mini-menu',
    'menu_id'         => '',
    'echo'            => true,
    'fallback_cb'     => 'wp_page_menu',
    'before'          => '',
    'after'           => '',
    'link_before'     => '',
    'link_after'      => '',
    'items_wrap'      => '<ul>%3$s</ul>',
    'depth'           => 0,
] );
